name: Language Sevice

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - run: |
        rm package-lock.json
        npm install
      working-directory: src/language-service

    - run: npm run compile
      working-directory: src/language-service

    - run: npm publish
      working-directory: src/language-service
      if: success() && github.ref == 'refs/heads/master'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}